name: Get Proxies

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  schedule:
    - cron: '0 12,23 * * *'

jobs:
  main:
    name: Merge & speedtest
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Set timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r  ./utils/requirements.txt
#    - name: Start Clash proxy environment
#      run: |
#        sudo sh ./utils/scripts/set_proxy.sh
    - name: Merge & speedtest
      run: |
        # --- 增加的调试步骤 ---
        echo "--- Debugging subconverter path and permissions ---"
        # 1. 检查 utils/subconverter 目录下的所有文件，看看到底叫什么名字
        ls -la ./utils/subconverter/
        
        # 2. 检查我们代码中使用的路径是否存在
        echo "Checking for existence of ./utils/subconverter/subconverter-linux-amd64"
        if [ -f "./utils/subconverter/subconverter-linux-amd64" ]; then
          echo "File FOUND."
        else
          echo "File NOT FOUND!"
        fi
        echo "--- End of Debugging ---"
        # --- 调试步骤结束 ---
        
        # 确保为正确的文件名添加执行权限
        # 假设通过 ls 发现它其实叫 subconverter
        # chmod +x ./utils/subconverter/subconverter 
        chmod +x ./utils/subconverter/subconverter-linux-amd64 

        # 执行主程序
        python3 ./utils/main.py
    - name: Commit change
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add ./sub
        git add ./update
        git add README.md
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并节点"
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: master
