name: Get Proxies

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  schedule:
    - cron: '0 12,23 * * *'

jobs:
  main:
    name: Merge & speedtest
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Set timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r  ./utils/requirements.txt
    - name: Merge & speedtest
      working-directory: ./utils
      run: |
        chmod +x ./subconverter/subconverter-linux-amd64 
        python3 main.py
    - name: Commit change
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add ./sub
        git add ./update
        git add README.md
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并节点"
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: master
